name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Basic test
      id: basic-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BASIC-TEST_RESULTS: "${{steps.basic-test.outputs.result}}"
      with:
        runners: basic-test
